### ISSUE TITLE
Raw SQL Queries

### ISSUE THREAD

**Issue by captchadex** [jhyman2/PostgreSQL-todo#1]
Why no http://docs.sequelizejs.com/?

**Comment by captchadex** [comment]
:trollface:

**Comment by jhyman2** [comment]
Excellent idea! Submit a PR for all of us at Hyman Co to review.

**Comment by captchadex** [comment]
Yes sir

**Comment by jhyman2** [comment]
https://i.imgflip.com/3bc7as.jpg

**Comment by jhyman2** [comment]
![image](https://user-images.githubusercontent.com/2983043/65453996-1aef5b00-ddf9-11e9-92dd-62d7f7b150a7.png)
